linters-settings:
  golint:
    min-confidence: 0

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - revive
    - ineffassign
    - gosimple
    - gomodguard
    - gofmt
    - unused
    - unconvert
    - gocritic
    - gofumpt
    - tenv
    - durationcheck
    - staticcheck

issues:
  exclude-use-default: false
  exclude:
      - should have a package comment
      - error strings should not be capitalized or end with punctuation or a newline
service:
  golangci-lint-version: 1.45.2 # use the fixed version to not introduce new linters unexpectedly
