version: 2

project_name: sidekick

release:
   name_template: "Release version {{.Version}}"

   github:
    owner: minio
    name: sidekick

before:
  hooks:
    - go mod tidy -compat=1.24

builds:
  -
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - --tags=kqueue
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  -
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary

nfpms:
  -
    vendor: MinIO, Inc.
    homepage: https://github.com/minio/sidekick
    maintainer: MinIO Development <dev@min.io>
    description: SideKick is a high-performance sidecar load-balancer.
    license: GNU Affero General Public License v3.0
    formats:
      - deb
      - rpm

signs:
  -
    signature: "${artifact}.minisig"
    cmd: "sh"
    args:
      - '-c'
      - 'minisign -s /media/${USER}/minio/minisign.key -Sm ${artifact} < /media/${USER}/minio/minisign-passphrase'
    artifacts: all

changelog:
  sort: asc

dockers:
- image_templates:
  - "quay.io/minio/sidekick:{{ .Tag }}-amd64"
  use: buildx
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  goarch: amd64
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "quay.io/minio/sidekick:{{ .Tag }}-ppc64le"
  use: buildx
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  goarch: ppc64le
  build_flag_templates:
  - "--platform=linux/ppc64le"
- image_templates:
  - "quay.io/minio/sidekick:{{ .Tag }}-s390x"
  use: buildx
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  goarch: s390x
  build_flag_templates:
  - "--platform=linux/s390x"
- image_templates:
  - "quay.io/minio/sidekick:{{ .Tag }}-arm64"
  use: buildx
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  goarch: arm64
  build_flag_templates:
  - "--platform=linux/arm64"
docker_manifests:
- name_template: quay.io/minio/sidekick:{{ .Tag }}
  image_templates:
  - quay.io/minio/sidekick:{{ .Tag }}-amd64
  - quay.io/minio/sidekick:{{ .Tag }}-arm64
  - quay.io/minio/sidekick:{{ .Tag }}-ppc64le
  - quay.io/minio/sidekick:{{ .Tag }}-s390x
